version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: python main.py

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    volumes:
      - .:/app
    command: python -m unittest discover

